# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: true
reviews:
  profile: "assertive"
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_in_walkthrough: true
  commit_status: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: true
  auto_review:
    enabled: true
    drafts: true
  tools:
    biome:
      enabled: true
chat:
  auto_reply: true
knowledge_base:
  opt_out: false
  web_search:
    enabled: false
  learnings:
    scope: "local"
  pull_requests:
    scope: "local"
